Repository bbta3-bppt/aeronitium, pull requests merged in 2021-03, with the labels that each got.

#1 Menyiapkan proses awal aplikasi utama
  Cargo.lock
  Cargo.toml
  README.md
  src/app/error.rs
  src/app/mod.rs
  src/main.rs
Labels: Maintenance

#2 Penambahan fungsi Re-Zero pneumatic pressure
  .gitignore
  Cargo.lock
  Cargo.toml
  src/app/decoders/mod.rs
  src/app/decoders/response_code.rs
  src/app/decoders/response_type.rs
  src/app/errors/ioerror.rs
  src/app/errors/mod.rs
  src/app/errors/sliceerror.rs
  src/app/helpers/calzero.rs
  src/app/helpers/firmware.rs
  src/app/helpers/mod.rs
  src/app/mod.rs
  src/app/models.rs
  src/main.rs
Labels: Maintenance

#3 Membuat fungsi awal ganti satuan
  src/app/helpers/calzero.rs
  src/app/helpers/chgunit.rs
  src/app/helpers/mod.rs
  src/main.rs
Labels: maintenance

#6 Simpan koefisien kalibrasi kedalam csv
  Cargo.lock
  Cargo.toml
  src/app/helpers/simplesetup.rs
  src/app/helpers/startarray.rs
Labels: maintenance

#7 Uji coba awal stream data sensor tekanan
  src/app/helpers/mod.rs
  src/app/helpers/output.rs
  src/app/helpers/simplesetup.rs
Labels: maintenance

#9 Membuat penambahan dan perubahan struktur aplikasi dtc
  Cargo.lock
  Cargo.toml
  README.md
  src/app/errors/enverror.rs
  src/app/errors/mod.rs
  src/app/handlers/mod.rs
  src/app/handlers/root.rs
  src/app/handlers/version.rs
  src/app/helpers/simplesetup.rs
  src/app/helpers/stream.rs
  src/app/middlewares.rs
  src/app/mod.rs
  src/app/routers.rs
  src/dtc/handlers/dtc.rs
  src/dtc/handlers/mod.rs
  src/dtc/mod.rs
  src/dtc/routers.rs
  src/main.rs
Labels: enhancement

#10 Menyatukan V0.2 ke dalam main branch
  Cargo.lock
  Cargo.toml
  README.md
  src/app/errors/enverror.rs
  src/app/errors/mod.rs
  src/app/handlers/mod.rs
  src/app/handlers/root.rs
  src/app/handlers/version.rs
  src/app/helpers/simplesetup.rs
  src/app/helpers/stream.rs
  src/app/middlewares.rs
  src/app/mod.rs
  src/app/routers.rs
  src/dtc/handlers/dtc.rs
  src/dtc/handlers/mod.rs
  src/dtc/mod.rs
  src/dtc/routers.rs
  src/main.rs
Labels: enhancement

#11 Pembuatan user interface awal berbasis text
  Cargo.lock
  Cargo.toml
  src/app/components/mod.rs
  src/app/components/sidebar.rs
  src/app/handlers/mod.rs
  src/app/handlers/root.rs
  src/app/handlers/version.rs
  src/app/layouts/default.rs
  src/app/layouts/mod.rs
  src/app/middlewares.rs
  src/app/mod.rs
  src/app/pages/mod.rs
  src/app/pages/root.rs
  src/app/routers.rs
  src/dtc/handlers/dtc.rs
  src/dtc/handlers/mod.rs
  src/dtc/mod.rs
  src/dtc/routers.rs
  src/main.rs
Labels: enhancement

#12 Membuat komponen kontainer awal
  src/app/components/sidebar.rs
  src/app/pages/coef_page.rs
  src/app/pages/connscanner_page.rs
  src/app/pages/daqparam_page.rs
  src/app/pages/firmware_page.rs
  src/app/pages/mod.rs
  src/app/pages/printcoef_page.rs
  src/app/pages/root.rs
  src/app/pages/scannerlist_page.rs
  src/app/pages/status_page.rs
  src/app/pages/stream_page.rs
  src/app/pages/unit_page.rs
Labels: maintenance

#13 Menerapkan closure untuk kebutuhan fungsi template
  src/app/components/container.rs
  src/app/components/info.rs
  src/app/components/mod.rs
  src/app/pages/coef_page.rs
  src/app/pages/connscanner_page.rs
  src/app/pages/daqparam_page.rs
  src/app/pages/firmware_page.rs
  src/app/pages/printcoef_page.rs
  src/app/pages/root.rs
  src/app/pages/scannerlist_page.rs
  src/app/pages/status_page.rs
  src/app/pages/stream_page.rs
  src/app/pages/unit_page.rs
Labels: maintenance

#14 Koreksi bug saat add_child
  Cargo.lock
  Cargo.toml
  src/app/pages/firmware_page.rs
Labels: maintenance

#15 Modifikasi struktur aeronitium kedalam server
  Cargo.lock
  Cargo.toml
  README.md
  src/app/components/container.rs
  src/app/components/info.rs
  src/app/components/mod.rs
  src/app/components/sidebar.rs
  src/app/configs.rs
  src/app/errors/ioerror.rs
  src/app/errors/mod.rs
  src/app/errors/responses.rs
  src/app/handlers/changeunit.rs
  src/app/handlers/connscanner.rs
  src/app/handlers/daqparams.rs
  src/app/handlers/eeprom.rs
  src/app/handlers/firmware.rs
  src/app/handlers/mod.rs
  src/app/handlers/root.rs
  src/app/handlers/scanlist.rs
  src/app/handlers/scannerstatus.rs
  src/app/handlers/tablecoef.rs
  src/app/helpers/display.rs
  src/app/helpers/initialization.rs
  src/app/helpers/output.rs
  src/app/helpers/simplesetup.rs
  src/app/helpers/stream.rs
  src/app/layouts/default.rs
  src/app/layouts/mod.rs
  src/app/mod.rs
  src/app/models.rs
  src/app/pages/coef_page.rs
  src/app/pages/connscanner_page.rs
  src/app/pages/daqparam_page.rs
  src/app/pages/firmware_page.rs
  src/app/pages/mod.rs
  src/app/pages/printcoef_page.rs
  src/app/pages/root.rs
  src/app/pages/scannerlist_page.rs
  src/app/pages/status_page.rs
  src/app/pages/stream_page.rs
  src/app/pages/unit_page.rs
  src/app/routers.rs
  src/main.rs
Labels: maintenance

#17 Update README
  README.md
Labels: documentation

#18 Membuat workflow draft rilis dan deploy aplikasi
  .github/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/upload.yaml
Labels: maintenance

#19 Membuat pengaturan parameter DTC kedalam ui
  .gitignore
  ui/.editorconfig
  ui/.eslintignore
  ui/.eslintrc.js
  ui/.postcssrc.js
  ui/README.md
  ui/aeronitium.png
  ui/babel.config.js
  ui/jsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/public/favicon.ico
  ui/public/icons/favicon-128x128.png
  ui/public/icons/favicon-16x16.png
  ui/public/icons/favicon-32x32.png
  ui/public/icons/favicon-96x96.png
  ui/quasar.conf.js
  ui/src-electron/electron-flag.d.ts
  ui/src-electron/icons/icon.icns
  ui/src-electron/icons/icon.ico
  ui/src-electron/icons/linux-512x512.png
  ui/src-electron/main-process/electron-main.dev.js
  ui/src-electron/main-process/electron-main.js
  ui/src/App.vue
  ui/src/assets/.gitkeep
  ui/src/boot/.gitkeep
  ui/src/boot/axios.js
  ui/src/components/banner/banner.js
  ui/src/components/banner/banner.vue
  ui/src/css/app.scss
  ui/src/css/font/jetbrains.woff2
  ui/src/css/includes/_base.scss
  ui/src/css/includes/_card.sass
  ui/src/css/includes/_typography.scss
  ui/src/css/quasar.variables.scss
  ui/src/index.template.html
  ui/src/layouts/default/MainLayout.vue
  ui/src/layouts/default/default.js
  ui/src/pages/Error404.vue
  ui/src/pages/configs/Configurations.vue
  ui/src/pages/configs/configs.js
  ui/src/pages/home/Home.vue
  ui/src/pages/home/home.js
  ui/src/router/index.js
  ui/src/router/routes.js
  ui/src/store/aeronitiummod/actions.js
  ui/src/store/aeronitiummod/getters.js
  ui/src/store/aeronitiummod/index.js
  ui/src/store/aeronitiummod/mutations.js
  ui/src/store/aeronitiummod/state.js
  ui/src/store/index.js
  ui/src/store/store-flag.d.ts
Labels: enhancement

#20 Pengembangan lanjut atur persiapan stream
  Cargo.lock
  Cargo.toml
  src/main.rs
  ui/package.json
  ui/quasar.conf.js
  ui/src-electron/main-process/electron-main.js
  ui/src/components/banner/banner.vue
  ui/src/css/includes/_base.scss
  ui/src/pages/configs/Configurations.vue
  ui/src/pages/configs/configs.js
  ui/src/pages/configs/helpers/check_stream.js
  ui/src/pages/configs/helpers/dtc.js
  ui/src/pages/configs/helpers/ocf.js
  ui/src/pages/configs/helpers/unx.js
  ui/src/pages/home/Home.vue
  ui/src/pages/home/home.js
  ui/src/store/aeronitiummod/getters.js
  ui/src/store/aeronitiummod/mutations.js
  ui/src/store/aeronitiummod/state.js
Labels: maintenance

#22 Update github workflow untuk unggah binary
  .github/workflows/upload.yaml
Labels: maintenance

#23 Membuat child thread untuk adapter Aeronitium
  Cargo.lock
  Cargo.toml
  README.md
  adapter/.gitignore
  adapter/bin/adapter.dart
  adapter/pubspec.lock
  adapter/pubspec.yaml
  src/app/configs.rs
  src/app/handlers/startstream.rs
  src/app/helpers/display.rs
  src/app/helpers/mod.rs
  src/app/helpers/process.rs
  src/app/helpers/stream.rs
  src/main.rs
Labels: maintenance

#24 Membuat github workflow awal untuk produksi
  .github/workflows/upload.yaml
Labels: sependencies

#25 Modifikasi dotenv dalam workflow
  .github/workflows/upload.yaml
Labels: sependencies

#26 Koreksi mv: cannot stat 'adaptor'
  .github/workflows/upload.yaml
Labels: sependencies

#27 Koreksi whitespace dan nama steps workflow
  .github/workflows/upload.yaml
Labels: dependencies

#28 Koreksi ls: cannot access 'aeronitium/'
  .github/workflows/upload.yaml
Labels: dependencies

#29 Menerapkan dotenv masing-masing service
  Cargo.lock
  Cargo.toml
  README.md
  screenshoot.png
  src/main.rs
  ui/package-lock.json
  ui/package.json
  ui/quasar.conf.js
  ui/src/pages/configs/helpers/dtc.js
Labels: documentation, maintenance

#30 Mempersiapkan bagian streaming sensor tekanan
  ui/package-lock.json
  ui/package.json
  ui/src/components/link/MainLink.vue
  ui/src/components/link/link.js
  ui/src/layouts/default/MainLayout.vue
  ui/src/layouts/default/default.js
  ui/src/pages/stream/Stream.vue
  ui/src/pages/stream/streaming.js
  ui/src/router/routes.js
Labels: maintenance

#32 Update judul repositori di release-drafter.yml
  .github/release-drafter.yml
Labels: dependencies
